include:
  - path: ../opal-fines-service/docker-compose.master.yml
  - path: ../opal-logging-service/docker-compose.master.yml
services:
  opal-user-service:
    image: opal-user-service:local
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy