apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-auth-service App
name: opal-opal-auth-service
home: https://github.com/hmcts/opal-auth-service
version: 0.0.17
maintainers:
  - name: HMCTS opal team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
